package com.example.ant.model.designer

val kDesigersMaps = listOf<String>(
    "Alexander McQueen",
    "Balenciaga",
    "Bottega Veneta",
    "Christian Louboutin",
    "Dolce & Gabbana",
    "Fendi",
    "Gucci",
    "Off-White",
    "Prada",
    "Saint Laurent",
    "Valentino",
)

val kDesignersAllMaps = mapOf<String, Int>(
    "Alexander McQueen" to 10565,
    "Dsquared2" to 8933,
    "Dolce & Gabbana" to 6707,
    "Valentino" to 5993,
    "Moschino" to 5007,
    "Versace" to 4369,
    "Off-White" to 4008,
    "Maison Margiela" to 3988,
    "Burberry" to 3969,
    "Etro" to 3882,
    "Balmain" to 3841,
    "Salvatore Ferragamo" to 3673,
    "Brunello Cucinelli" to 3554,
    "Marsèll" to 3400,
    "Hogan" to 3385,
    "Saint Laurent" to 3285,
    "Stuart Weitzman" to 3262,
    "Pinko" to 3164,
    "Herno" to 3153,
    "Stella McCartney" to 3088,
    "Palm Angels" to 3027,
    "MSGM" to 2972,
    "Balenciaga" to 2971,
    "Golden Goose Deluxe Brand" to 2916,
    "Jil Sander" to 2840,
    "Polo Ralph Lauren" to 2833,
    "Marni" to 2729,
    "Kenzo" to 2709,
    "Isabel Marant" to 2596,
    "Givenchy" to 2476,
    "Tod's" to 2475,
    "A.P.C." to 2354,
    "Just Cavalli" to 2039,
    "Michael Michael Kors" to 2038,
    "Nike" to 2024,
    "Bottega Veneta" to 1836,
    "C.P. Company" to 1816,
    "Thom Browne" to 1769,
    "Jimmy Choo" to 1607,
    "Max Mara" to 1605,
    "Chiara Ferragni" to 1554,
    "Tory Burch" to 1543,
    "Elisabetta Franchi" to 1531,
    "P.A.R.O.S.H." to 1510,
    "GCDS" to 1501,
    "Isabel Marant Étoile" to 1451,
    "Woolrich" to 1451,
    "Moncler Enfant" to 1442,
    "Rick Owens" to 1434,
    "Chloé" to 1432,
    "Moncler" to 1401,
    "Diesel" to 1379,
    "Adidas Originals" to 1366,
    "MM6 Maison Margiela" to 1319,
    "JW Anderson" to 1296,
    "Lanvin" to 1289,
    "RED Valentino" to 1283,
    "Tom Ford" to 1271,
    "Dsquared2 Kids" to 1265,
    "Vans" to 1263,
    "Ambush" to 1251,
    "Acne Studios" to 1184,
    "Barbour" to 1181,
    "Heron Preston" to 1177,
    "Amiri" to 1163,
    "Fendi" to 1149,
    "Moschino Kids" to 1128,
    "Koché" to 1124,
    "Vetements" to 1113,
    "Balmain Kids" to 1112,
    "Marcelo Burlon County Of Milan" to 1107,
    "Giuseppe Zanotti" to 1101,
    "Jacquemus" to 1101,
    "Bally" to 1100,
    "Comme des Garçons Play" to 1054,
    "Versace Jeans Couture" to 1051,
    "Church's" to 1040,
    "Stone Island" to 1022,
    "The Attico" to 1015,
    "Ganni" to 1001,
    "Maison Kitsuné" to 998,
    "1017 ALYX 9SM" to 963,
    "Missoni" to 960,
    "See By Chloé" to 959,
    "'S Max Mara" to 955,
    "Prada" to 937,
    "Paris Texas" to 928,
    "AMI" to 926,
    "Canada Goose" to 922,
    "Stella McCartney Kids" to 919,
    "Max Mara Studio" to 918,
    "Sportmax" to 912,
    "The North Face" to 911,
    "Y-3" to 908,
    "Gianvito Rossi" to 907,
    "Dr. Martens" to 901,
    "Love Moschino" to 901,
    "Fay" to 897,
    "Comme des Garçons Shirt" to 890,
    "Emporio Armani" to 866,
    "Gucci Kids" to 847,
    "Veja" to 824,
    "Philosophy Di Lorenzo Serafini" to 820,
    "Boss Hugo Boss" to 803,
    "Miu Miu" to 798,
    "Nanushka" to 786,
    "Alexander Wang" to 763,
    "Philippe Model Paris" to 763,
    "Self-Portrait" to 751,
    "By Far" to 749,
    "Burberry Kids" to 722,
    "Golden Goose Kids" to 714,
    "Weekend Max Mara" to 712,
    "Khaite" to 700,
    "Moose Knuckles" to 662,
    "Z Zegna" to 658,
    "Off-White Kids" to 643,
    "Paul Smith" to 640,
    "Alberta Ferretti" to 636,
    "Raf Simons" to 623,
    "Adidas" to 610,
    "McQ Alexander McQueen" to 606,
    "Rick Owens DRKSHDW" to 596,
    "Marine Serre" to 584,
    "Zimmermann" to 578,
    "PS Paul Smith" to 574,
    "Frame" to 571,
    "Paco Rabanne" to 570,
    "Sacai" to 560,
    "Dries Van Noten" to 553,
    "GIA BORGHINI" to 550,
    "Givenchy Kids" to 548,
    "Stone Island Junior" to 536,
    "Alanui" to 524,
    "Sporty & Rich" to 523,
    "Ermenegildo Zegna" to 517,
    "Philipp Plein" to 516,
    "Ash" to 513,
    "Il Gufo" to 510,
    "Chloé Kids" to 501,
    "Aries" to 500,
    "Marc Jacobs" to 494,
    "Aquazzura" to 492,
    "Gucci Eyewear" to 491,
    "Kenzo Kids" to 491,
    "Puma" to 486,
    "Palm Angels Kids" to 473,
    "Helmut Lang" to 469,
    "Lemaire" to 465,
    "Versace Kids" to 464,
    "Giorgio Armani" to 462,
    "Adidas By Stella McCartney" to 460,
    "Sergio Rossi" to 455,
    "A-Cold-Wall*" to 449,
    "TWINSET" to 445,
    "Loewe" to 444,
    "Fendi Kids" to 442,
    "Philippe Model" to 440,
    "Aspesi" to 438,
    "Iro" to 431,
    "Prada Eyewear" to 424,
    "Neil Barrett" to 414,
    "Autry" to 411,
    "Carhartt WIP" to 407,
    "Karl Lagerfeld" to 405,
    "Alessandra Rich" to 403,
    "Alexander McQueen Kids" to 402,
    "ASICS" to 396,
    "Moncler Genius" to 396,
    "Tricker's" to 395,
    "Alexandre Vauthier" to 394,
    "MSGM Kids" to 388,
    "Michael Kors" to 387,
    "Barrow" to 379,
    "ROTATE" to 379,
    "Theory" to 369,
    "MCM" to 367,
    "Manebí" to 362,
    "Totême" to 359,
    "Boutique Moschino" to 358,
    "Comme des Garçons Wallet" to 350,
    "Stone Island Shadow Project" to 348,
    "Hugo Boss Kids" to 340,
    "Furla" to 339,
    "Malo" to 327,
    "Sunnei" to 314,
    "Guidi" to 309,
    "Wandler" to 309,
    "Axel Arigato" to 306,
    "The Marc Jacobs Kids" to 306,
    "Zadig & Voltaire" to 306,
    "Common Projects" to 301,
    "Martine Rose" to 298,
    "Dolce & Gabbana Kids" to 296,
    "Mini Rodini" to 288,
    "Oséree" to 288,
    "Chiara Ferragni Kids" to 269,
    "Christian Louboutin" to 268,
    "Eytys" to 267,
    "Herno Kids" to 264,
    "Ray-Ban" to 262,
    "Ralph Lauren Kids" to 253,
    "Saint Laurent Eyewear" to 245,
    "Sebago" to 241,
    "The Row" to 241,
    "Gucci" to 235,
    "Y/Project" to 228,
    "DKNY Kids" to 227,
    "Billionaire Boys Club" to 224,
    "Proenza Schouler White Label" to 221,
    "Manolo Blahnik" to 220,
    "Staud" to 220,
    "Cartier" to 219,
    "Rene Caovilla" to 218,
    "Hugo" to 215,
    "Maison Michel" to 213,
    "Tommy Hilfiger" to 212,
    "Marni Kids" to 208,
    "MM6 Maison Margiela Kids" to 205,
    "Ih Nom Uh Nit" to 202,
    "Coperni" to 201,
    "Junya Watanabe" to 200,
    "Pt01" to 199,
    "Kiton" to 198,
    "Moncler Grenoble" to 194,
    "Uma Wang" to 194,
    "Bonpoint" to 190,
    "Comme des Garçons Homme Plus" to 190,
    "UGG Kids" to 190,
    "Casablanca" to 188,
    "Persol" to 188,
    "Barena" to 187,
    "Mi Mi Sol" to 186,
    "Proenza Schouler" to 185,
    "Zanellato" to 184,
    "Longchamp" to 183,
    "AGOLDE" to 182,
    "Tom Ford Eyewear" to 180,
    "Loro Piana" to 179,
    "Versace Eyewear" to 176,
    "Tartine et Chocolat" to 175,
    "Reina Olga" to 173,
    "Clarks" to 171,
    "Dior Homme" to 171,
    "Burberry Eyewear" to 169,
    "GCDS Kids" to 169,
    "Andersson Bell" to 166,
    "Hugo Boss" to 166,
    "T By Alexander Wang" to 163,
    "Balenciaga Kids" to 159,
    "Evisu" to 159,
    "Birkenstock" to 158,
    "Disclaimer" to 158,
    "N°21 Kids" to 154,
    "Chloé Eyewear" to 151,
    "Save The Duck Kids" to 150,
    "Maison Mihara Yasuhiro" to 148,
    "Misbhv" to 147,
    "Boyy" to 146,
    "Emilio Pucci Junior" to 145,
    "PT Torino" to 140,
    "Courrèges" to 139,
    "Dolce & Gabbana Eyewear" to 139,
    "Premiata" to 139,
    "Woolrich Kids" to 138,
    "Bottega Veneta Eyewear" to 135,
    "Veja Kids" to 135,
    "Officine Creative" to 134,
    "Max Mara The Cube" to 131,
    "C.P. Company Kids" to 130,
    "Comme des Garçons" to 130,
    "3.1 Phillip Lim" to 129,
    "John Lobb" to 128,
    "Needles" to 128,
    "Mulberry" to 124,
    "Marcelo Burlon County Of Milan Kids" to 122,
    "Billieblush" to 121,
    "Fila" to 120,
    "Paolo Pecora" to 120,
    "Ralph Lauren" to 120,
    "Valentino Eyewear" to 115,
    "Belstaff" to 110,
    "OAMC" to 108,
    "Mykita" to 105,
    "Alexander McQueen Eyewear" to 104,
    "Emporio Armani Kids" to 102,
    "Ballantyne" to 100,
    "Yuzefi" to 99,
    "Fear of God" to 94,
    "Reebok" to 94,
    "Max Mara Leisure" to 93,
    "RE/DONE" to 93,
    "Cult Gaia" to 92,
    "Converse" to 91,
    "Hinnominate" to 91,
    "La Stupenderia" to 91,
    "Rombaut" to 91,
    "Suicoke" to 90,
    "Spalwart" to 89,
    "Opening Ceremony" to 86,
    "Black Comme des Garçons" to 82,
    "L'Autre Chose" to 82,
    "Balenciaga Eyewear" to 81,
    "Monnalisa" to 80,
    "Retrosuperfuture" to 80,
    "Manu Atelier" to 74,
    "Rixo" to 74,
    "Parajumpers" to 73,
    "Yohji Yamamoto" to 73,
    "Vision Of Super" to 72,
    "Junya Watanabe MAN" to 71,
    "Magda Butrym" to 71,
    "Roger Vivier" to 71,
    "Brunello Cucinelli Kids" to 70,
    "MOUTY" to 70,
    "Simonetta" to 70,
    "Les Coyotes De Paris" to 66,
    "Vans Vault" to 66,
    "N°21" to 65,
    "Saint James" to 65,
    "Amen" to 64,
    "Montblanc" to 64,
    "Fornasetti" to 63,
    "Emile Et Ida" to 62,
    "Margaret Howell" to 62,
    "Alysi" to 61,
    "J Brand" to 61,
    "Rick Owens X Veja" to 61,
    "Swarovski" to 60,
    "Unravel Project" to 60,
    "Cutler & Gross" to 59,
    "Si Rossi" to 59,
    "Amina Muaddi" to 58,
    "Ann Demeulemeester" to 58,
    "Anya Hindmarch" to 58,
    "Barba" to 57,
    "APM Monaco" to 54,
    "Arkair" to 54,
    "Etro Home" to 54,
    "Loulou Studio" to 54,
    "Ruslan Baginskiy" to 54,
    "Ulla Johnson" to 54,
    "Mother" to 53,
    "Marni Eyewear" to 52,
    "Pt05" to 52,
    "Engineered Garments" to 51,
    "Junya Watanabe Comme des Garçons" to 51,
    "Mc2 Saint Barth" to 51,
    "Comme des Garçons Noir Kei Ninomiya" to 50,
    "Comme des Garçons Comme des Garçons" to 49,
    "Nicholas Kirkwood" to 49,
    "Paraboot" to 49,
    "Thom Browne Eyewear" to 48,
    "Tiffany & Co." to 48,
    "YMC" to 48,
    "John Smedley" to 47,
    "Patou" to 46,
    "Enterprise Japan" to 45,
    "Ma.strum" to 45,
    "Mansur Gavriel" to 45,
    "Arizona Love" to 44,
    "Lardini" to 44,
    "Boglioli" to 43,
    "Sunflower" to 43,
    "Honey Fucking Dijon" to 42,
    "MARKET" to 41,
    "Stand Studio" to 41,
    "UGG" to 40,
    "Mach & Mach" to 39,
    "Missoni Home" to 38,
    "Alpha Industries" to 37,
    "Fucking Awesome" to 37,
    "Givenchy Eyewear" to 36,
    "Buscemi" to 34,
    "Homme Plissé Issey Miyake" to 34,
    "Oliver Peoples" to 34,
    "Red Wing Shoes" to 34,
    "Vivienne Westwood" to 34,
    "Comme des Garçons Play Kids" to 33,
    "Nick Fouquet" to 33,
    "R13" to 33,
    "La Doublej" to 32,
    "Save The Duck" to 32,
    "Ancient Greek Sandals" to 31,
    "Carhartt" to 31,
    "Mugler" to 31,
    "Buttero" to 30,
    "Mackintosh" to 30,
    "Michael Kors Collection" to 30,
    "Adidas By Wales Bonner" to 29,
    "Universal Works" to 29,
    "Marques'Almeida" to 28,
    "Raf Simons X Fred Perry" to 28,
    "Wolford" to 27,
    "Area" to 26,
    "Co" to 26,
    "Juun J" to 26,
    "Robert Clergerie" to 26,
    "Baracuta" to 25,
    "Ea7 Emporio Armani" to 25,
    "Represent" to 25,
    "Chinatown Market" to 24,
    "Coach" to 24,
    "Dita Eyewear" to 24,
    "Dsquared2 Eyewear" to 24,
    "Liu Jo" to 24,
    "Mou Kids" to 24,
    "New Balance" to 24,
    "Themoirè" to 24,
    "KAPPA" to 23,
    "Low Classic" to 23,
    "PACCBET" to 23,
    "Tagliatore" to 23,
    "Diemme" to 22,
    "Finamore 1925 Napoli" to 21,
    "Alaïa" to 20,
    "Baum Und Pferdgarten" to 20,
    "Collina Strada" to 20,
    "Lanvin Enfant" to 20,
    "Balmain Eyewear" to 19,
    "Bao Bao Issey Miyake" to 19,
    "L'Objet" to 19,
    "Nodaleto" to 19,
    "Telfar" to 19,
    "Undercover" to 19,
    "Ienki Ienki" to 18,
    "Issey Miyake" to 18,
    "Monobi" to 18,
    "White Mountaineering" to 18,
    "Yeezy" to 17,
    "Andrea Adamo" to 16,
    "Apesi" to 16,
    "M Missoni" to 16,
    "Rag & Bone" to 16,
    "Jacques Marie Mage" to 15,
    "Jejia" to 15,
    "Missoni Mare" to 15,
    "Moncler Eyewear" to 15,
    "Stella McCartney Eyewear" to 15,
    "1/OFF" to 14,
    "C2H4" to 14,
    "Dkny" to 14,
    "Emilio Pucci" to 14,
    "Levi's" to 14,
    "Philosophy Di Lorenzo Serafini Kids" to 14,
    "Rhude" to 14,
    "Tatras" to 14,
    "ANT45" to 13,
    "Berluti" to 13,
    "Castañer" to 13,
    "Hoka One One" to 13,
    "Pharmacy Industry" to 13,
    "REMAIN Birger Christensen" to 13,
    "Amazuìn" to 12,
    "Blue Sky Inn" to 12,
    "Comme des Garçons Girl" to 12,
    "Diane von Furstenberg" to 12,
    "Rodebjer" to 12,
    "Seletti" to 12,
    "South2 West8" to 12,
    "Visvim" to 12,
    "We11done" to 12,
    "#09 Profumi" to 11,
    "Eudon Choi" to 11,
    "Studio Nicholson" to 11,
    "Allsaints" to 10,
    "Aragona" to 10,
    "Equipment" to 10,
    "Linda Farrow" to 10,
    "Malone Souliers" to 10,
    "Rick Owens Lilies" to 10,
    "Ten C" to 10,
    "Cecilie Bahnsen" to 9,
    "Drôle de Monsieur" to 9,
    "Fendi Eyewear" to 9,
    "Francesco Russo" to 9,
    "Maisie Wilen" to 9,
    "Marchesa Notte" to 9,
    "Moschino Eyewear" to 9,
    "Reebok X Victoria Beckham" to 9,
    "Simone Rocha" to 9,
    "Valextra" to 9,
    "ANOUKI" to 8,
    "Ader Error" to 8,
    "Billionaire" to 8,
    "Canada Goose Kids" to 8,
    "Dior Eyewear" to 8,
    "Gedebe" to 8,
    "Hunza G" to 8,
    "Philosophy by Lorenzo Serafini" to 8,
    "R.M.Williams" to 8,
    "Saloni" to 8,
    "Courrèges Eyewear" to 7,
    "Dion Lee" to 7,
    "Jimmy Choo Eyewear" to 7,
    "Kara" to 7,
    "Lamborghini" to 7,
    "Ottolinger" to 7,
    "Adidas Kids" to 6,
    "Ermanno Scervino" to 6,
    "Harris Wharf London" to 6,
    "Helen Kaminski" to 6,
    "Kappa Kontroll" to 6,
    "Khrisjoy Kids" to 6,
    "Napa By Martine Rose" to 6,
    "Neous" to 6,
    "Qeeboo" to 6,
    "Salvatore Piccolo" to 6,
    "VTMNTS" to 6,
    "Adidas By Pharrell Williams" to 5,
    "Ajmone" to 5,
    "Allude" to 5,
    "Aniye By" to 5,
    "Au Départ" to 5,
    "Car Shoe" to 5,
    "Diesel Red Tag" to 5,
    "Garrett Leight" to 5,
    "Kangol" to 5,
    "Lauren Ralph Lauren" to 5,
    "Marysia" to 5,
    "NICOMEDE" to 5,
    "Noon Goons" to 5,
    "Prps" to 5,
    "Rejina Pyo" to 5,
    "Repetto" to 5,
    "Casadei" to 4,
    "Extreme Cashmere" to 4,
    "Gabriela Hearst" to 4,
    "Hogan Kids" to 4,
    "MATÉRIEL" to 4,
    "Moncler + Rick Owens" to 4,
    "Paul & Shark" to 4,
    "Pierre Hardy" to 4,
    "Pleats Please By Issey Miyake" to 4,
    "Purple Brand" to 4,
    "Stüssy" to 4,
    "Versace Jeans" to 4,
    "7 For All Mankind" to 3,
    "Agnona" to 3,
    "Alanui Kids" to 3,
    "Bulgari" to 3,
    "Citizens of Humanity" to 3,
    "Edward Green" to 3,
    "Fabiana Filippi" to 3,
    "Fay Kids" to 3,
    "Fenty X Puma" to 3,
    "Haider Ackermann" to 3,
    "K-Way Kids" to 3,
    "Khrisjoy" to 3,
    "Orciani" to 3,
    "Our Legacy" to 3,
    "Rebecca Minkoff" to 3,
    "Reike Nen" to 3,
    "Saks Potts" to 3,
    "Shrimps" to 3,
    "Adidas By Raf Simons" to 2,
    "Adriana Degreas" to 2,
    "Blancha" to 2,
    "Coliac" to 2,
    "Corneliani" to 2,
    "District Vision" to 2,
    "Dodo Bar Or" to 2,
    "Etre Cecile" to 2,
    "Forte Forte" to 2,
    "Isaia" to 2,
    "Le Kasha" to 2,
    "Marc Jacobs Eyewear" to 2,
    "Polo Ralph Lauren Kids" to 2,
    "Rave Review" to 2,
    "Readymade" to 2,
    "Salomon S/Lab" to 2,
    "Salvatore Santoro" to 2,
    "Simonetta Ravizza" to 2,
    "Sofie D'hoore" to 2,
    "A.W.A.K.E. Mode" to 1,
    "Adidas By Danielle Cathari" to 1,
    "Alberta Ferretti Kids" to 1,
    "Arma" to 1,
    "Brian Dales" to 1,
    "Chopova Lowena" to 1,
    "Comme des Garçons Shirt Boys" to 1,
    "Cutler And Gross" to 1,
    "Diadora" to 1,
    "Diesel Kids" to 1,
    "Eckhaus Latta" to 1,
    "Elie Saab" to 1,
    "Faith Connexion" to 1,
    "Fallon" to 1,
    "Gallery Dept." to 1,
    "Giambattista Valli" to 1,
    "Gosha Rubchinskiy" to 1,
    "Hereu" to 1,
    "Kuboraum" to 1,
    "MJB Marc Jacques Burton" to 1,
    "Manokhi" to 1,
    "Mauna Kea" to 1,
    "Max Mara Pianoforte" to 1,
    "Miu Miu Eyewear" to 1,
    "Moncler Gamme Bleu" to 1,
    "Peter Do" to 1,
    "Pierre-Louis Mascia" to 1,
    "Plan C" to 1,
    "Ports 1961" to 1,
    "Simon Miller" to 1,
    "Ssheena" to 1,
    "Tommy Jeans" to 1,
    "Uh Nom Uh Nit" to 1,
    "Wales Bonner" to 1,
    "Zanone" to 1,
    "Саlvin Кlеin Kids" to 1
)